title: Tiddlywiki Plugin Skeleton
description: Develop TiddlyWiki5 Plugins using ThirdFlow.
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/TheDiveO/TiddlyWikiPluginSkeleton/zipball/master
  tar_url: https://github.com/TheDiveO/TiddlyWikiPluginSkeleton/tarball/master
gems:
  - jekyll-mentions
